import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import uitnodigingRouter from "./uitnodiging";
import dashboardRouter from "./dashboard";
import gebouwenRouter from "./gebouwen";
import voorzieningenRouter from "./voorzieningen";
import classificatieRouter from "./classificatie";
import fabrikantenRouter from "./fabrikanten";
import documentenRouter from "./documenten";
import inspectiesRouter from "./inspecties";
import onderhoudRouter from "./onderhoud";
import gebruikersRouter from "./gebruikers";
import abonnementenRouter from "./abonnementen";
import storageRouter from "./storage";
import systeemRouter from "./systeem";
import infoRouter from "./info";
import crmRouter from "./crm";
import inboxRouter from "./inbox";
import emailsRouter from "./emails";
import profielenRouter from "./profielen";
import hrmRouter from "./hrm";
import dossiersRouter from "./dossiers";
import offertesRouter from "./offertes";
import portaalRouter from "./portaal";
import mailRouter from "./mail";
import calculatiesRouter from "./calculaties";
import rapportenRouter from "./rapporten";
import constructieTemplatesRouter from "./constructie-templates";
import mijnWerkRouter from "./mijn-werk";
import mijnPrivacyRouter from "./mijn-privacy";
import toolboxRouter from "./toolbox";
import planningModuleRouter from "./planning-module";
import modCalculatieRouter from "./mod-calculatie";
import gereedschappenRouter from "./gereedschappen";
import wagenparkRouter from "./wagenpark";
import { achievementsRouter } from "./achievements";
import urenRouter from "./uren";
import chatRouter from "./chat";
import backupsRouter from "./backups";
import herstelRouter from "./herstel";
import opnameRouter from "./opname";
import werkdagRouter from "./werkdag";
import projectenRouter from "./projecten";
import spotStatusConfiguratieRouter from "./spot-status-configuratie";
import werkInboxRouter from "./werk-inbox";
import veiligheidRouter from "./veiligheid";
import opdrachtenRouter from "./opdrachten";
import werkvoorbereidingRouter from "./werkvoorbereiding";
import snagstreamRouter from "./snagstream";
import facturenRouter from "./facturen";
import instellingenAccountviewRouter from "./instellingen-accountview";
import accountviewMappingRouter from "./accountview-mapping";
import salarisarchiefRouter from "./salarisarchief";
import goLiveRouter from "./golive";
import salarisMutatiesRouter from "./salaris-mutaties";
import scabMailRouter from "./scab-mail";
import boekhouderRouter from "./boekhouder";
import loonOutputRouter from "./loon-output";
import slimUploadRouter from "./slim-upload";
import workflowRouter from "./workflow";
import onlineGebruikersRouter from "./online-gebruikers";
import nieuwsRouter from "./nieuws";
import organisatieRouter from "./organisatie";
import leveranciersRouter from "./leveranciers";
import artikelenRouter from "./artikelen";
import importRouter from "./import";
import onderhandenWerkRouter from "./onderhanden-werk";
import onderhoudscontractenRouter from "./onderhoudscontracten";
import werkbonnenRouter from "./werkbonnen";
import magazijnRouter from "./magazijn";
import studioRouter from "./studio";
import aiRouter from "./ai";
import { requireAuth } from "../middlewares/auth";
import { meldActief } from "../lib/online-tracker";

const router: IRouter = Router();

// Publieke routes
router.use(healthRouter);
router.use(authRouter);
router.use(uitnodigingRouter);
router.use(portaalRouter);
// Vanaf hier vereist alles een geldige sessie
router.use(requireAuth);
// Online-aanwezigheid bijhouden (debounced, fire-and-forget)
router.use((req, _res, next) => {
  const uid = req.session?.userId;
  if (uid) meldActief(uid).catch(() => {});
  next();
});

router.use(dashboardRouter);
router.use(gebouwenRouter);
router.use(voorzieningenRouter);
router.use(classificatieRouter);
router.use(fabrikantenRouter);
router.use(documentenRouter);
router.use(inspectiesRouter);
router.use(onderhoudRouter);
router.use(gebruikersRouter);
router.use(abonnementenRouter);
router.use(storageRouter);
router.use(systeemRouter);
router.use(infoRouter);
router.use(crmRouter);
router.use(inboxRouter);
router.use(emailsRouter);
router.use(profielenRouter);
router.use(hrmRouter);
router.use(dossiersRouter);
router.use(offertesRouter);
router.use(mailRouter);
router.use(calculatiesRouter);
router.use(rapportenRouter);
router.use(constructieTemplatesRouter);
router.use(mijnWerkRouter);
router.use(mijnPrivacyRouter);
router.use(toolboxRouter);
router.use(planningModuleRouter);
router.use(modCalculatieRouter);
router.use(gereedschappenRouter);
router.use(urenRouter);
router.use(achievementsRouter);
router.use(chatRouter);
router.use(backupsRouter);
router.use(herstelRouter);
router.use(opnameRouter);
router.use(werkdagRouter);
router.use(projectenRouter);
router.use(spotStatusConfiguratieRouter);
router.use(werkInboxRouter);
router.use(veiligheidRouter);
router.use(opdrachtenRouter);
router.use(werkvoorbereidingRouter);
router.use(snagstreamRouter);
router.use(facturenRouter);
router.use(instellingenAccountviewRouter);
router.use(accountviewMappingRouter);
router.use(salarisarchiefRouter);
router.use(goLiveRouter);
router.use(salarisMutatiesRouter);
router.use(scabMailRouter);
router.use(boekhouderRouter);
router.use(loonOutputRouter);
router.use(slimUploadRouter);
router.use(workflowRouter);
router.use(onlineGebruikersRouter);
router.use("/wagenpark", wagenparkRouter);
router.use(nieuwsRouter);
router.use(organisatieRouter);
router.use(leveranciersRouter);
router.use(artikelenRouter);
router.use(importRouter);
router.use(onderhandenWerkRouter);
router.use(onderhoudscontractenRouter);
router.use(werkbonnenRouter);
router.use(magazijnRouter);
router.use(studioRouter);
router.use(aiRouter);

export default router;
