import { Router, type IRouter } from "express";
import healthRouter from "./health";
import uitrolRouter from "./uitrol";
import authRouter from "./auth";
import uitnodigingRouter from "./uitnodiging";
import installatieRouter from "./installatie";
import dashboardRouter from "./dashboard";
import gebouwenRouter from "./gebouwen";
import voorzieningenRouter from "./voorzieningen";
import gebouwNotitiesRouter from "./gebouw-notities";
import classificatieRouter from "./classificatie";
import fabrikantenRouter from "./fabrikanten";
import documentenRouter from "./documenten";
import inspectiesRouter from "./inspecties";
import onderhoudRouter from "./onderhoud";
import gebruikersRouter from "./gebruikers";
import abonnementenRouter from "./abonnementen";
import storageRouter from "./storage";
import systeemRouter from "./systeem";
import infoRouter from "./info";
import crmRouter from "./crm";
import aanvragenRouter from "./aanvragen";
import inboxRouter from "./inbox";
import emailsRouter from "./emails";
import profielenRouter from "./profielen";
import hrmRouter from "./hrm";
import externeAdviseursRouter from "./externe-adviseurs";
import uitzendbureauKoppelingenRouter from "./uitzendbureau-koppelingen";
import hrmWizardRouter from "./hrm-wizard";
import dossiersRouter from "./dossiers";
import financieleContractenRouter from "./financiele-contracten";
import offertesRouter from "./offertes";
import portaalRouter from "./portaal";
import mailRouter from "./mail";
import calculatiesRouter from "./calculaties";
import rapportenRouter from "./rapporten";
import constructieTemplatesRouter from "./constructie-templates";
import mijnWerkRouter from "./mijn-werk";
import mijnPrivacyRouter from "./mijn-privacy";
import mijnVoorkeurenRouter from "./mijnVoorkeuren";
import momentsRouter from "./moments";
import toolboxRouter from "./toolbox";
import planningModuleRouter from "./planning-module";
import modCalculatieRouter from "./mod-calculatie";
import modCalculatieImportRouter from "./mod-calculatie-import";
import gereedschappenRouter from "./gereedschappen";
import wagenparkRouter from "./wagenpark";
import wagenparkMeldingenRouter from "./wagenpark-meldingen";
import documentsoortenRouter from "./documentsoorten";
import { achievementsRouter } from "./achievements";
import adviseurRouter from "./adviseur";
import urenRouter from "./uren";
import chatRouter from "./chat";
import backupsRouter from "./backups";
import mailWachtrijRouter from "./mail-wachtrij";
import actiepuntenRouter from "./actiepunten";
import acceptatieregisterRouter from "./acceptatieregister";
import kalenderRouter from "./kalender";
import herstelRouter from "./herstel";
import opnameRouter from "./opname";
import werkdagRouter from "./werkdag";
import projectenRouter from "./projecten";
import spotStatusConfiguratieRouter from "./spot-status-configuratie";
import werkInboxRouter from "./werk-inbox";
import veiligheidRouter from "./veiligheid";
import opdrachtenRouter from "./opdrachten";
import werkvoorbereidingRouter from "./werkvoorbereiding";
import snagstreamRouter from "./snagstream";
import facturenRouter from "./facturen";
import instellingenAccountviewRouter from "./instellingen-accountview";
import grootboekRouter from "./grootboek";
import betaalbatchRouter from "./betaalbatch";
import accountviewMappingRouter from "./accountview-mapping";
import salarisarchiefRouter from "./salarisarchief";
import goLiveRouter from "./golive";
import salarisMutatiesRouter from "./salaris-mutaties";
import scabMailRouter from "./scab-mail";
import boekhouderRouter from "./boekhouder";
import loonOutputRouter from "./loon-output";
import slimUploadRouter from "./slim-upload";
import workflowRouter from "./workflow";
import onlineGebruikersRouter from "./online-gebruikers";
import nieuwsRouter from "./nieuws";
import organisatieRouter from "./organisatie";
import leveranciersRouter from "./leveranciers";
import artikelenRouter from "./artikelen";
import prijsafsprakenRouter from "./prijsafspraken";
import marktspiegelRouter from "./marktspiegel";
import importRouter from "./import";
import onderhandenWerkRouter from "./onderhanden-werk";
import onderhoudscontractenRouter from "./onderhoudscontracten";
import werkbonnenRouter from "./werkbonnen";
import inkoopOverzichtRouter from "./inkoop-overzicht";
import algemeneInkoopRouter from "./algemene-inkoop";
import magazijnRouter from "./magazijn";
import materiaalAanvragenRouter from "./materiaal-aanvragen";
import metingenMateriaalRouter from "./metingen-materiaal";
import metingenAkkoordRouter from "./metingen-akkoord";
import metingenBewakingRouter from "./metingen-bewaking";
import uitvoerderRouter from "./uitvoerder";
import studioRouter from "./studio";
import aiRouter from "./ai";
import aiBeslissingenRouter from "./ai-beslissingen";
import { pbmRouter } from "./pbm";
import { regieRouter } from "./regie";
import contractBewakingRouter from "./contract-bewaking";
import meldingenRouter from "./meldingen";
import eenheidsprijzenRouter from "./eenheidsprijzen";
import fieRouter from "./fie";
import pimRouter from "./pim";
import uitvoeringRouter from "./uitvoering";
import kbRouter from "./kb";
import visualsRouter from "./visuals";
import { requireAuth, laadPermissies, blokkeerBijWachtwoordWijzigenVereist } from "../middlewares/auth";
import { meldActief } from "../lib/online-tracker";
import { maakAuditMiddleware } from "../lib/audit";
import { governanceMiddleware } from "../middlewares/governance";
import governanceRouter from "./governance";
import securityQuarantaineRouter from "./security-quarantine";
import auditRouter from "./audit";
import objectRechtenRouter from "./object-rechten";
import aiLogRouter from "./ai-log";
import aiContextRouter from "./ai-context";
import avgRouter from "./avg";
import visualLibraryRouter from "./visual-library";
import securityValidationRouter from "./security-validation";
import { cqoRouter } from "./cqo";
import kantoorReleaseRouter from "./kantoor-release";
import financieelJaarrekeningenRouter from "./financieel-jaarrekeningen";
import goedkeuringRouter from "./goedkeuring";
import declaratiesRouter from "./declaraties";
import directiecockpitRouter from "./directiecockpit";
import biaeRouter from "./biae";
import werkbakRouter from "./werkbak";
import werkstroomRouter from "./werkstroom";
import "../services/workflow-configs";
import wervingRouter from "./werving";
import marketingRouter, { marketingPubliekRouter } from "./marketing";
import socialRouter from "./social";
import merkenkastRouter from "./merkenkast";
import beeldbankRouter from "./beeldbank";
import functiesV2Router from "./functies-v2";
import bankafschriftenRouter from "./bankafschriften";
import loonfundamentRouter from "./loonfundament";

const router: IRouter = Router();

// Publieke routes
router.use(healthRouter);
// UITROL_BEWAKING_01: terugmelding van de deploy-runner — publiek pad,
// beveiligd met gedeelde sleutel (zie routes/uitrol.ts), dus vóór requireAuth.
router.use(uitrolRouter);
router.use(authRouter);
router.use(uitnodigingRouter);
router.use(installatieRouter);
router.use(portaalRouter);
// MARKETING_01: afmelden zonder inloggen (publieke token)
router.use(marketingPubliekRouter);
// Vanaf hier vereist alles een geldige sessie
router.use(requireAuth);
// Fail-closed: een verplichte wachtwoordwijziging (na admin-reset) blokkeert
// alle overige routes hier onder /api, ongeacht wat de client stuurt.
// /auth/* blijft bereikbaar omdat die router hierboven al is afgehandeld.
router.use(blokkeerBijWachtwoordWijzigenVereist);
// Laad permissies één keer per request — req.permissies beschikbaar op alle routes
router.use(laadPermissies);
// KLANTLOOS_01: Connect is klantloos — de vroegere klant-toegangspoort is
// verwijderd; alle autorisatie loopt via de module-rechtencontrole per route.
// Universele audit trail — onderschept alle muterende requests
router.use(maakAuditMiddleware());
// AI Governance & Risk Engine — beoordeelt iedere schrijfactie, blokkeert kritieke operaties
router.use(governanceMiddleware);
// Online-aanwezigheid bijhouden (debounced, fire-and-forget)
router.use((req, _res, next) => {
  const uid = req.session?.userId;
  if (uid) meldActief(uid).catch(() => {});
  next();
});

router.use(dashboardRouter);
router.use(gebouwenRouter);
router.use(voorzieningenRouter);
router.use(gebouwNotitiesRouter);
router.use(classificatieRouter);
router.use(fabrikantenRouter);
router.use(documentenRouter);
router.use(inspectiesRouter);
router.use(onderhoudRouter);
router.use(gebruikersRouter);
router.use(abonnementenRouter);
router.use(storageRouter);
router.use(systeemRouter);
router.use(infoRouter);
router.use(crmRouter);
router.use(marketingRouter);
router.use(socialRouter);
router.use(merkenkastRouter);
router.use(beeldbankRouter);
router.use(aanvragenRouter);
router.use(inboxRouter);
router.use(emailsRouter);
router.use(profielenRouter);
router.use(hrmRouter);
router.use(functiesV2Router);
router.use(externeAdviseursRouter);
router.use(uitzendbureauKoppelingenRouter);
router.use(hrmWizardRouter);
router.use(dossiersRouter);
router.use(offertesRouter);
router.use(mailRouter);
router.use(calculatiesRouter);
router.use(rapportenRouter);
router.use(constructieTemplatesRouter);
router.use(mijnWerkRouter);
router.use(mijnPrivacyRouter);
router.use(mijnVoorkeurenRouter);
router.use(momentsRouter);
router.use(toolboxRouter);
router.use(planningModuleRouter);
router.use(modCalculatieImportRouter);
router.use(modCalculatieRouter);
router.use(gereedschappenRouter);
router.use(urenRouter);
router.use(achievementsRouter);
router.use(chatRouter);
router.use(backupsRouter);
router.use(mailWachtrijRouter);
router.use(actiepuntenRouter);
router.use(acceptatieregisterRouter);
router.use(kalenderRouter);
router.use(herstelRouter);
router.use(opnameRouter);
router.use(werkdagRouter);
router.use(projectenRouter);
router.use(spotStatusConfiguratieRouter);
router.use(werkInboxRouter);
router.use(veiligheidRouter);
router.use(opdrachtenRouter);
router.use(werkvoorbereidingRouter);
router.use(wervingRouter);
router.use(snagstreamRouter);
router.use(facturenRouter);
router.use(instellingenAccountviewRouter);
router.use(grootboekRouter);
router.use(betaalbatchRouter);
router.use(accountviewMappingRouter);
router.use(salarisarchiefRouter);
router.use(goLiveRouter);
router.use(salarisMutatiesRouter);
router.use(scabMailRouter);
router.use(boekhouderRouter);
router.use(loonOutputRouter);
router.use(slimUploadRouter);
router.use(workflowRouter);
router.use(onlineGebruikersRouter);
router.use("/wagenpark", wagenparkRouter);
router.use("/wagenpark", wagenparkMeldingenRouter);
router.use(documentsoortenRouter);
router.use(nieuwsRouter);
router.use(organisatieRouter);
router.use(leveranciersRouter);
router.use(artikelenRouter);
router.use(prijsafsprakenRouter);
router.use(marktspiegelRouter);
router.use(importRouter);
router.use(onderhandenWerkRouter);
router.use(onderhoudscontractenRouter);
router.use(werkbonnenRouter);
router.use(inkoopOverzichtRouter);
router.use(algemeneInkoopRouter);
router.use(magazijnRouter);
router.use(materiaalAanvragenRouter);
router.use(metingenMateriaalRouter);
router.use(metingenAkkoordRouter);
router.use(metingenBewakingRouter);
router.use(uitvoerderRouter);
router.use(studioRouter);
router.use(aiRouter);
router.use(aiContextRouter);
router.use(aiBeslissingenRouter);
router.use(pbmRouter);
router.use(regieRouter);
router.use(contractBewakingRouter);
router.use(meldingenRouter);
router.use(eenheidsprijzenRouter);
router.use(fieRouter);
router.use(pimRouter);
router.use(uitvoeringRouter);
router.use(kbRouter);
router.use(visualsRouter);
router.use(auditRouter);
router.use(objectRechtenRouter);
router.use(governanceRouter);
router.use(securityQuarantaineRouter);
router.use(aiLogRouter);
router.use(avgRouter);
router.use(visualLibraryRouter);
router.use(securityValidationRouter);
router.use(cqoRouter);
router.use(kantoorReleaseRouter);
router.use(financieelJaarrekeningenRouter);
router.use(goedkeuringRouter);
router.use(declaratiesRouter);
router.use(directiecockpitRouter);
router.use(biaeRouter);
router.use(adviseurRouter);
router.use(financieleContractenRouter);
router.use(werkbakRouter);
// WERKBAK_02 — vóór de generieke werkbak-routes met /:id zou niet eens nodig
// zijn (paden verschillen), maar expliciete volgorde voorkomt schaduw.
router.use(werkstroomRouter);
router.use(bankafschriftenRouter);
// LOON_02A — Loonfundament: inkomstenverhoudingen, loonafspraken, jaarparameters en loonstaten.
router.use(loonfundamentRouter);

export default router;
