// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fps-atelier/Dashboard.tsx": () => import("../components/mockups/fps-atelier/Dashboard.tsx"),
  "./components/mockups/gebouwpagina/PlattegrondEerst.tsx": () => import("../components/mockups/gebouwpagina/PlattegrondEerst.tsx"),
  "./components/mockups/gebouwpagina/PlattegrondHero.tsx": () => import("../components/mockups/gebouwpagina/PlattegrondHero.tsx"),
  "./components/mockups/gebouwpagina/SplitWerkruimte.tsx": () => import("../components/mockups/gebouwpagina/SplitWerkruimte.tsx"),
  "./components/mockups/nav-prototype/NavPrototype.tsx": () => import("../components/mockups/nav-prototype/NavPrototype.tsx"),
  "./components/mockups/fps-horizon/Dashboard.tsx": () => import("../components/mockups/fps-horizon/Dashboard.tsx"),
  "./components/mockups/fps-lumiere/Dashboard.tsx": () => import("../components/mockups/fps-lumiere/Dashboard.tsx")
};
