kind = "web"
previewPath = "/"
title = "FPS Brandpreventie"
version = "1.0.0"
id = "artifacts/firevault"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25392

[services.development]
run = "pnpm --filter @workspace/firevault run dev"

[services.env]
PORT = "25392"
BASE_PATH = "/"
