import { pgTable, serial, integer, text, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";

export const securityIntakeScansTable = pgTable("security_intake_scans", {
  id: serial("id").primaryKey(),
  gebruikerId: integer("gebruiker_id"),
  gebruikerNaam: text("gebruiker_naam"),
  uploadBron: text("upload_bron").notNull().default("document"),
  bestandsnaam: text("bestandsnaam"),
  bestandsgrootte: integer("bestandsgrootte"),
  mimeTypeClaim: text("mime_type_claim"),
  mimeTypeWerkelijk: text("mime_type_werkelijk"),
  objectPad: text("object_pad"),
  documentId: integer("document_id"),
  emailOnderwerp: text("email_onderwerp"),
  extensieStatus: text("extensie_status").notNull().default("niet_gescand"),
  mimeStatus: text("mime_status").notNull().default("niet_gescand"),
  structuurStatus: text("structuur_status").notNull().default("niet_gescand"),
  linkStatus: text("link_status").notNull().default("niet_gescand"),
  aiStatus: text("ai_status").notNull().default("niet_gescand"),
  clamavStatus: text("clamav_status").notNull().default("niet_beschikbaar"),
  risicoNiveau: text("risico_niveau").notNull().default("groen"),
  risicoBevindingen: jsonb("risico_bevindingen"),
  linksGeanalyseerd: jsonb("links_geanalyseerd"),
  aiSamenvatting: text("ai_samenvatting"),
  actie: text("actie").notNull().default("toegestaan"),
  blokkeerReden: text("blokker_reden"),
  inQuarantaine: boolean("in_quarantaine").notNull().default(false),
  quarantaineReden: text("quarantaine_reden"),
  beoordeeldDoorId: integer("beoordeeld_door_id"),
  beoordeeldDoorNaam: text("beoordeeld_door_naam"),
  beoordelingOpmerking: text("beoordeling_opmerking"),
  beoordeeldOp: timestamp("beoordeeld_op"),
  aangemaaktOp: timestamp("aangemaakt_op").notNull().defaultNow(),
  bijgewerktOp: timestamp("bijgewerkt_op").notNull().defaultNow(),
});
